### ISSUE TITLE
Project completion checklist

### ISSUE THREAD

**Issue by WylfredWen** [JiayuanWen/Belloc-More-Beasts#31]
### Curation work:

- [x] Needs to be represented and fully readable on your GitHub Pages website.
- [x] Must share image view(s) of the source document you worked with, paired with your encoding of data and metadata expressed in markup, visualized in HTML.
- [x] Must represent your team's work with XML, XSLT, HTML, and CSS, as well as image and file curation.
- [x] Must do something more than just represent all the words in the source document. Your work should survey and highlight how you categorized and organized features and metadata in the source document.
- [x] Should make some interesting pattern become visible or easy to navigate. Provide a table of contents, some highlighting, and a survey of interesting words/names pulled from your markup.
- [x] Explain your team's approach to the markup, what you agreed to follow and study with it. (You can link or make a feature of your schema if that's easy to read, but also explain some of your coding decisions to people who don't know the project as you and I do.)
- [x] Should share information you learned from working with the documents: (For example, what did the team learn about the Behrends and their connections, about events in their lives, about things they cared about, about historic objects, people etc? Tell what you learned from the documents somewhere on the site.)
- [x] Link us to related resources about this document or the writer/people involved with it.
- [x] Cite your sources for images and material that you use that did not originate with you and your project team. Where appropriate, provide direct links to the main pages of these resources. (For example, link an image to its source, putting the URL of the source in a @title attribute on the \<img\> element, or including the linked source in a caption.)
- [x] Credit the project team: introduce the team and what each of you contributed to the project.

### Site Organization:
- [x] Your GitHub Pages site should be publishing from a docs directory in your project GitHub repository. 
- [x] The site should consist of multiple pages, and hold a site menu that clearly and effectively guides readers.
- [x] You need a title for your project to use at least on the main site page.
- [x] Your main page should be named index.html, and needs to describe what site visitors will learn from exploring this site.
- [x] Use the \<head\> . . . \</head\> element in HTML effectively to hold each page's distinct title (to view in tabbed browsers), and give each page a clear title in the appropriate heading elements (h1, h2, h3, etc) in HTML.
- [x] You should have a separate CSS file that is linked the \<head\>...\</head\> element. of your HTML file
- [x] Apply relative links to files on your site, and be sure your web directory is well organized so that your code functions (no broken links or mistargeted file associations). 
- [x] Include some documentation of the code you wrote: Your site should include a page inviting visitors (especially those interested in learning to code), to view and study your most significant code work: XML, Relax NG, XSLT, CSS.
- [x] When you represent your code, discuss your decisions in coding your project and processing the output.
- [x] Sites must link in some way to the "code view" of the project repo. You can work with this to feature the code you wrote for the project.
- [x] Sites should feature a Creative Commons License of the team's choice.

Full assignment: https://psu.instructure.com/courses/2193254/assignments/14553586

**Comment by WylfredWen** [comment]
@ebeshero The project is completed and ready for evaluation.
